import type { Metadata } from "next";
import "@/app/globals.css";

import { ThemeWrapper } from "./context/theme-context";
import SessionAuthContext from "./context/session-context";
import UserProvider from "./context/user-context";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Suspense fallback={<Loading />}>
          <ThemeWrapper
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange={true}
            enableSystem={true}
          >
            <SessionAuthContext>
              <UserProvider>
                {children}
                <Toaster />
              </UserProvider>
            </SessionAuthContext>
          </ThemeWrapper>
        </Suspense>
      </body>
    </html>
  );
}
